# -*- coding: utf-8 -*-
"""Ip.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KRzoNjrZHCQ0ugEvn5wOBhSQCrwEZp21
"""

import cv2
from google.colab.patches import cv2_imshow

import torch
import numpy as np
import torchvision.transforms as transforms

from google.colab import drive
drive.mount('/content/gdrive')

!cd 'gdrive/My Drive'

#!cd 'Thermal Imaging'
!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd gdrive
!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd 'My Drive'
!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd 'Thermal Imaging'
!ls

img = cv2.imread("9.jpg")
cv2_imshow(img)

imgneg=cv2.bitwise_not(img)
cv2_imshow(imgneg)

ret,thresh1=cv2.threshold(img,127,255,cv2.THRESH_BINARY)

cv2_imshow(thresh1)

import numpy as np
img=cv2.imread("9.jpg",0)
img=img.astype('float64')
row,col=img.shape
lt=60
ut=215
img1=np.array(np.zeros((row,col),np.uint8))
for x in range(row):
  for y in range(col):
    if img[x][y]<=lt:
      img1[x][y]=0.5*img[x][y]
    elif img[x][y]<=ut:
      img1[x][y]=2*(img[x][y]-lt)+(0.5)*lt
    else: img1[x][y]=0.5*(img[x][y]-ut)+0.5*lt+2*(ut-lt)

cv2_imshow(img1)

from matplotlib import pyplot as plt
img=cv2.imread('9.jpg',0)
row,col=img.shape
img1=np.array(np.zeros((row,col),np.uint8))
for x in range(row):
  for y in range(col):
    if img[x][y]==0:
      img[x][y]=0
histr=cv2.calcHist([img],[0],None,[256],[0,256])
plt.plot(histr)
plt.show()

